# -*- coding: utf-8 -*-
"""Text-to-Speech Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYFSd6Kg4dfBNag0no3Nwqpd99rMxt-c
"""

!pip install transformers

!pip install  soundfile

!pip install gradio

from transformers import AutoTokenizer, AutoModelForTextToWaveform

tokenizer = AutoTokenizer.from_pretrained("facebook/mms-tts-eng")
model = AutoModelForTextToWaveform.from_pretrained("facebook/mms-tts-eng")

import torch
import soundfile as sf

def text_to_speech(text):
    inputs = tokenizer(text, return_tensors="pt")
    with torch.no_grad():
        waveform = model(**inputs).waveform[0]
    sf.write("output.wav", waveform.numpy(), 16000)
    return "output.wav"

import gradio as gr

def generate_audio(text):
    audio_file = text_to_speech(text)
    return audio_file

interface = gr.Interface(
    fn=generate_audio,
    inputs="text",
    outputs="audio",
    title="Text-to-Speech Chatbot",
    description="Enter text and hear it spoken aloud by the model."
)

interface.launch()